https://x.com/Bybit_Official/status/1772579293421301824?s=20# This is a basic workflow to help you get started with Actions
alAa_alNaSeR7
name: CI@alAa_alNaSeR7

# Controls when the workflow will run
on:
  # TrTKwj6xGvQw2pDPxpK3pPTdBWoseWWbeuhpiggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: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

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:https://x.com/Bybit_Official/status/1772579293421301824?s=20
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
